### ISSUE TITLE
Unable to run setup.py for python

### ISSUE THREAD

**Issue by vibhoraggarwal** [OpenSimulationInterface/open-simulation-interface#393]
#### Description
Unable to install OSI for python on my Windows 10 PC using the command `python setup.py install`.  It gives me the error: `... google/protobuf/descriptor.proto: File not found.
osi3/osi_version.proto: Import "google/protobuf/descriptor.proto" was not found or had errors.
osi3/osi_version.proto:51:8: "google.protobuf.FileOptions" is not defined.
Traceback (most recent call last):...`  (full log below)

#### Things already done

1. In my Environment variables, I have already defined PYTHONPATH=`/path/to/protobuf/src/google/`

2. As python could not locate `/protobuf/src/google/`, so I added `sys.path.insert(1, '/path/to/application/app/folder')` in `setup.py` but still the same error as below pops up.
3. I have also tried installing it with a previous version of [Protobuf ](https://github.com/protocolbuffers/protobuf) (`v2.6.1`)but it still shows me the same error.

I have the following versions of pre-requisites installed:
`Python 3.8.3`
`Protobuf v3.12.3`

#### Clarifying the query
I am not sure if it is a problem with Protocol buffer library, or I am doing something wrong. If you have any suggestion about this issue please let me know. 

#### Error log on the command prompt
It gives me the following error:
```
running install
running bdist_egg
running egg_info
writing open_simulation_interface.egg-info\PKG-INFO
writing dependency_links to open_simulation_interface.egg-info\dependency_links.txt
writing requirements to open_simulation_interface.egg-info\requires.txt
writing top-level names to open_simulation_interface.egg-info\top_level.txt
reading manifest file 'open_simulation_interface.egg-info\SOURCES.txt'
writing manifest file 'open_simulation_interface.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
Protobuf-compiling osi_version.proto
google/protobuf/descriptor.proto: File not found.
osi3/osi_version.proto: Import "google/protobuf/descriptor.proto" was not found or had errors.
osi3/osi_version.proto:51:8: "google.protobuf.FileOptions" is not defined.
Traceback (most recent call last):
  File "setup.py", line 103, in <module>
    setup(
  File "C:\Users\AGV2FE\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\AGV2FE\AppData\Local\Programs\Python\Python38-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\AGV2FE\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\AGV2FE\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\AGV2FE\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\AGV2FE\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\AGV2FE\AppData\Local\Programs\Python\Python38-32\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\AGV2FE\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\AGV2FE\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\AGV2FE\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "C:\Users\AGV2FE\AppData\Local\Programs\Python\Python38-32\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\AGV2FE\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\AGV2FE\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\AGV2FE\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\install_lib.py", line 105, in build
    self.run_command('build_py')
  File "C:\Users\AGV2FE\AppData\Local\Programs\Python\Python38-32\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\AGV2FE\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 87, in run
    subprocess.check_call([self.find_protoc(),
  File "C:\Users\AGV2FE\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\git\\protobuf-2.6.1\\vsprojects\\Debug\\protoc.exe', '--python_out=.', 'osi3\\osi_version.proto']' returned non-zero exit status 1. ```

**Comment by vibhoraggarwal** [comment]
As mentioned in the error log above:
```
Protobuf-compiling osi_version.proto
google/protobuf/descriptor.proto: File not found.
osi3/osi_version.proto: Import "google/protobuf/descriptor.proto" was not found or had errors.
osi3/osi_version.proto:51:8: "google.protobuf.FileOptions" is not defined.

```

I had to copy the `google/` folder from the `protobuf/src` to successfully install it. 

I will close the issue for now. If somebody has any comment or a workaround in the script to avoid manual copying feel free to open it again.
